global using mark.davison.athens.shared.models.dtos.Scenarios.Queries.FetchTaskInstances;
global using mark.davison.athens.shared.models.Entities;
global using mark.davison.athens.shared.queries.Scenarios.FetchTaskInstances;
global using mark.davison.common.server.abstractions.Authentication;
global using mark.davison.common.server.abstractions.Identification;
global using mark.davison.common.server.abstractions.Repository;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using NSubstitute;
global using System.Linq.Expressions;