name: build

on: 
  workflow_dispatch:
  push:
    branches: [ main, dev, 'dev/*', 'feature/*', 'rel/*' ]
    paths-ignore:
      - readme.md
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_NOLOGO: true
  CI_BUILD: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          submodules: recursive
          fetch-depth: 0
          
      - name: Install WebCompiler
        run: dotnet tool install Excubo.WebCompiler --global

      - name: build web artifacts
        working-directory: ./src
        run: webcompiler ./web/mark.davison.athens.web.ui/compilerconfig.json
        
      - name: dump web artifacts - 1
        working-directory: ./src
        run: cat ./web/mark.davison.athens.web.ui/wwwroot/css/athens.css
      - name: dump web artifacts - 2
        working-directory: ./src
        run: cat ./web/mark.davison.athens.web.ui/wwwroot/css/athens.min.css

      - name: build
        working-directory: ./src
        run: dotnet build

      - name: test
        working-directory: ./src
        run: dotnet test --filter "TestCategory!=UI"